/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOrderStatusRouteImport } from './routes/api/public/order-status'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicVerifyPaymentRouteImport } from './routes/api/public/verify-payment'
import { Route as ApiPublicWelcomeEmailRouteImport } from './routes/api/public/welcome-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderStatusRoute = ApiPublicOrderStatusRouteImport.update({
  id: '/api/public/order-status',
  path: '/api/public/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyPaymentRoute = ApiPublicVerifyPaymentRouteImport.update({
  id: '/api/public/verify-payment',
  path: '/api/public/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWelcomeEmailRoute = ApiPublicWelcomeEmailRouteImport.update({
  id: '/api/public/welcome-email',
  path: '/api/public/welcome-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/welcome-email': typeof ApiPublicWelcomeEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/welcome-email': typeof ApiPublicWelcomeEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/verify-payment': typeof ApiPublicVerifyPaymentRoute
  '/api/public/welcome-email': typeof ApiPublicWelcomeEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/order-status'
    | '/api/public/orders'
    | '/api/public/verify-payment'
    | '/api/public/welcome-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/order-status'
    | '/api/public/orders'
    | '/api/public/verify-payment'
    | '/api/public/welcome-email'
  id:
    | '__root__'
    | '/'
    | '/api/public/order-status'
    | '/api/public/orders'
    | '/api/public/verify-payment'
    | '/api/public/welcome-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicOrderStatusRoute: typeof ApiPublicOrderStatusRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicVerifyPaymentRoute: typeof ApiPublicVerifyPaymentRoute
  ApiPublicWelcomeEmailRoute: typeof ApiPublicWelcomeEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-status': {
      id: '/api/public/order-status'
      path: '/api/public/order-status'
      fullPath: '/api/public/order-status'
      preLoaderRoute: typeof ApiPublicOrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-payment': {
      id: '/api/public/verify-payment'
      path: '/api/public/verify-payment'
      fullPath: '/api/public/verify-payment'
      preLoaderRoute: typeof ApiPublicVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/welcome-email': {
      id: '/api/public/welcome-email'
      path: '/api/public/welcome-email'
      fullPath: '/api/public/welcome-email'
      preLoaderRoute: typeof ApiPublicWelcomeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicOrderStatusRoute: ApiPublicOrderStatusRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
  ApiPublicVerifyPaymentRoute: ApiPublicVerifyPaymentRoute,
  ApiPublicWelcomeEmailRoute: ApiPublicWelcomeEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
